### ISSUE TITLE
update the ubuntu package

### ISSUE THREAD

**Issue by iambumblehead** [mnemosyne-proj/mnemosyne#37]
https://launchpad.net/ubuntu/artful/+source/mnemosyne

ubuntu currently provides version 2.4. There are some important additions in 2.5 and 2.6 for high-resolution screens, so it would be great if 2.6 were packaged instead.

Thanks :)

**Comment by three-comrades** [comment]
AFAIK Ubuntu syncs from Debian (testing?) every six months. So, I guess long-term we need to find out why Debian doesn't update the package. I've been wanting to do this for quite some time ... I'll try to look into it this week and report back.

**Comment by iambumblehead** [comment]
I tried building an [ubuntu-style 'snap' package][1] for mnemosyne but encountered [this issue.][0] I've not made a snap before.

It _should_ work for someone building the snap from LTS ubuntu.
*snapcraft.yaml*
```yaml
name: mnemosyne # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Optimized Flashcards and Research Project # 79 char long summary
description: |
  a free, open-source, spaced-repetition flashcard program that helps you
  learn as efficiently as possible.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  mnemosyne:
    source: .
    plugin: python
    python-version: python3

apps:
  mnemosyne:
    command: python3 mnemosyne/pyqt_ui/mnemosyne
```

[0]: https://github.com/canonical-websites/tutorials.ubuntu.com/issues/550
[1]: https://docs.snapcraft.io/build-snaps/python
